apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hwid-node<SUFFIX>
  name: hwid-node<SUFFIX>
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hwid-node<SUFFIX>
    spec:
      containers:
      - image: gcr.io/google.com/croshwid<SUFFIX>/factory_hwid_service:<VERSION-TAG>
        name: hwid-node<SUFFIX>
        ports:
        - containerPort: 8181
