apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hwid-node<SUFFIX>
  name: hwid-node<SUFFIX>
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hwid-node<SUFFIX>
    spec:
      containers:
      - image: gcr.io/google.com/croshwid<SUFFIX>/factory_hwid_service:<VERSION-TAG>
        name: hwid-node<SUFFIX>
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hwid-service<SUFFIX>
  name: hwid-service<SUFFIX>
spec:
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  selector:
    name: hwid-node<SUFFIX>
  type: LoadBalancer
  loadBalancerIP: <IP>
